### ISSUE TITLE
i got the error"No such file or directory: 'TownCentre-groundtruth.top"

### ISSUE THREAD

**Issue by aa12356jm** [ZidanMusk/experimenting-with-sort#2]
where could i find the file? thanks very much

**Comment by JVLegend** [comment]
Here it is: http://www.robots.ox.ac.uk/~lav/Research/Projects/2009bbenfold_headpose/project.html

**Comment by kubark42** [comment]
Can I suggest that all relevant data be checked into the git repo? Those links might eventually disappear, and it stands as a barrier to easy experimentation.

The issues at
https://github.com/ZidanMusk/experimenting-with-sort/issues/1
https://github.com/ZidanMusk/experimenting-with-sort/issues/3
https://github.com/ZidanMusk/experimenting-with-sort/issues/8
are all in some way flowing from the missing data.

**Comment by cmendozab** [comment]
The "TownCentre-groundtruth.top" file doesn't appear to be found anywhere.

**Comment by cmendozab** [comment]
@JVLegend 
Hello, this may be a long shot but, could you share the file "TownCentre-groundtruth.top"? 
The original webpage from Oxford is not available anymore. I have been looking around for this .top file to run some example codes which requires it. So far no luck finding the original file.

**Comment by joaoantoniocardoso** [comment]
@cmendozab see [here](https://academictorrents.com/details/35e83806d9362a57be736f370c821960eb2f2a01).
